import Link from "next/link";
import { LeagueCard } from "@/components/LeagueCard";
import { MatchCard } from "@/components/MatchCard";
import { LEAGUES } from "@odds-collector/shared";
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { toSlug } from "@/lib/url-utils";
import "@/styles/page.css";
import "@/styles/home-preview.css";

// Revalidate every 30 minutes
export const revalidate = 1800;

// Types matching the pre-computed aggregate data from collector
interface SteamMovePreview {
  leagueId: string;
  matchKey: string;
  homeTeam: string;
  awayTeam: string;
  kickoffTime: string;
  marketLabel: string;
  outcome: string;
  bookmaker: string;
  fromOdds: number;
  toOdds: number;
  movement: number;
  direction: "shortening" | "drifting";
}

interface UpcomingMatch {
  key: string;
  homeTeam: string;
  awayTeam: string;
  kickoffTime: string;
  matchDate: string;
  snapshots: Record<string, string>;
  leagueId: string;
  leagueName: string;
}

interface HomepageAggregate {
  upcomingMatches: UpcomingMatch[];
  recentSteamMoves: SteamMovePreview[];
  generatedAt: string;
}

/**
 * Fetch pre-computed homepage data from R2
 * This data is generated by the collector cron job
 */
async function getHomePageData(): Promise<{
  upcomingMatches: UpcomingMatch[];
  recentSteamMoves: SteamMovePreview[];
}> {
  try {
    const { env } = await getCloudflareContext({ async: true });
    const bucket = env.ODDS_BUCKET;

    // Read pre-computed homepage aggregate
    const homepageObject = await bucket.get("odds_data_v2/aggregates/homepage.json");

    if (!homepageObject) {
      console.log("Homepage aggregate not found, returning empty data");
      return {
        upcomingMatches: [],
        recentSteamMoves: [],
      };
    }

    const homepage: HomepageAggregate = await homepageObject.json();

    return {
      upcomingMatches: homepage.upcomingMatches,
      recentSteamMoves: homepage.recentSteamMoves,
    };
  } catch (error) {
    console.error("Error fetching homepage data:", error);
    return {
      upcomingMatches: [],
      recentSteamMoves: [],
    };
  }
}

export default async function HomePage() {
  const { upcomingMatches, recentSteamMoves } = await getHomePageData();

  return (
    <div className="page">
      <header className="page__header">
        <h1 className="page__title">Bookmaker Intelligence</h1>
        <p className="page__subtitle">
          Track odds movements across 4 snapshot timings. Identify steam moves
          and market sentiment.
        </p>
      </header>

      <section className="page__section">
        <h2 className="page__section-title">Select a League</h2>
        <div className="grid grid--cols-2">
          {LEAGUES.map((league) => (
            <LeagueCard key={league.id} league={league} />
          ))}
        </div>
      </section>

      {/* Upcoming Matches Preview */}
      <section className="page__section">
        <div className="page__section-header">
          <h2 className="page__section-title page__section-title--muted">
            Upcoming Matches
          </h2>
          <Link href="/leagues/england-premier-league" className="page__view-all" prefetch={false}>
            View all →
          </Link>
        </div>
        {upcomingMatches.length > 0 ? (
          <div className="home-preview__matches">
            {upcomingMatches.map((item) => (
              <MatchCard
                key={`${item.leagueId}-${item.key}`}
                match={{
                  key: item.key,
                  homeTeam: item.homeTeam,
                  awayTeam: item.awayTeam,
                  matchDate: item.matchDate,
                  kickoffTime: item.kickoffTime,
                  snapshots: item.snapshots,
                  eventId: "",
                }}
                leagueId={item.leagueId}
                leagueName={item.leagueName}
              />
            ))}
          </div>
        ) : (
          <p className="home-preview__empty">No upcoming matches in the next 7 days</p>
        )}
      </section>

      {/* Recent Steam Moves Preview */}
      <section className="page__section">
        <div className="page__section-header">
          <h2 className="page__section-title page__section-title--muted">
            Recent Steam Moves
          </h2>
          <Link href="/steam-moves" className="page__view-all" prefetch={false}>
            View all →
          </Link>
        </div>
        {recentSteamMoves.length > 0 ? (
          <div className="home-preview__steam-moves">
            {recentSteamMoves.map((move, idx) => (
              <Link
                key={idx}
                href={`/leagues/${toSlug(move.leagueId)}/matches/${toSlug(move.matchKey)}`}
                className={`home-preview__steam-move home-preview__steam-move--${move.direction}`}
              >
                <div className="home-preview__steam-move-match">
                  {move.homeTeam} vs {move.awayTeam}
                </div>
                <div className="home-preview__steam-move-details">
                  <span className="home-preview__steam-move-market">
                    {move.marketLabel}: {move.outcome}
                  </span>
                  <span className="home-preview__steam-move-bookmaker">
                    {move.bookmaker}
                  </span>
                </div>
                <div className="home-preview__steam-move-change">
                  <span className="home-preview__steam-move-odds">
                    {move.fromOdds.toFixed(2)} → {move.toOdds.toFixed(2)}
                  </span>
                  <span
                    className={`home-preview__steam-move-pct home-preview__steam-move-pct--${move.direction}`}
                  >
                    {move.direction === "shortening" ? "↓" : "↑"}{" "}
                    {Math.abs(move.movement).toFixed(1)}%
                  </span>
                </div>
              </Link>
            ))}
          </div>
        ) : (
          <p className="home-preview__empty">
            No significant steam moves detected for upcoming matches
          </p>
        )}
      </section>
    </div>
  );
}
