import { Breadcrumb } from "@/components/Breadcrumb";
import { SteamMovesClient } from "@/components/SteamMovesClient";
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { LEAGUES, CURRENT_SEASON } from "@odds-collector/shared";
import "@/styles/steam-moves-page.css";

// Revalidate every 30 minutes
export const revalidate = 1800;

export interface SteamMove {
  leagueId: string;
  matchKey: string;
  homeTeam: string;
  awayTeam: string;
  kickoffTime: string;
  market: string;
  marketLabel: string;
  outcome: string;
  point?: number;
  fromTiming: string;
  toTiming: string;
  bookmaker: string;
  fromOdds: number;
  toOdds: number;
  movement: number;
  direction: "shortening" | "drifting";
}

export interface SteamMovesData {
  season: string;
  steamMoves: SteamMove[];
  generatedAt: string;
  availableMarkets: string[];
  hasMorePast: boolean;
}

// Pre-computed aggregate structure from collector
interface LeagueSteamMovesAggregate {
  leagueId: string;
  season: string;
  steamMoves: SteamMove[];
  generatedAt: string;
  availableMarkets: string[];
}

/**
 * Fetch pre-computed steam moves from R2
 * This data is generated by the collector cron job with caching for past matches
 */
async function getSteamMoves(): Promise<SteamMovesData> {
  const season = CURRENT_SEASON;

  try {
    const { env } = await getCloudflareContext({ async: true });
    const bucket = env.ODDS_BUCKET;

    const allSteamMoves: SteamMove[] = [];
    const allMarkets = new Set<string>();

    // Read pre-computed steam moves for each league
    for (const league of LEAGUES) {
      const steamMovesKey = `odds_data_v2/leagues/${league.id}/${season}/steam_moves.json`;
      const steamMovesObject = await bucket.get(steamMovesKey);

      if (!steamMovesObject) continue;

      const aggregate: LeagueSteamMovesAggregate = await steamMovesObject.json();
      allSteamMoves.push(...aggregate.steamMoves);
      aggregate.availableMarkets.forEach((m) => allMarkets.add(m));
    }

    // Sort by kickoff time (chronologically)
    allSteamMoves.sort(
      (a, b) => new Date(a.kickoffTime).getTime() - new Date(b.kickoffTime).getTime()
    );

    return {
      season,
      steamMoves: allSteamMoves,
      generatedAt: new Date().toISOString(),
      availableMarkets: Array.from(allMarkets).sort(),
      hasMorePast: false, // All data is now in the aggregate
    };
  } catch (error) {
    console.error("Error fetching steam moves:", error);
    return {
      season,
      steamMoves: [],
      generatedAt: new Date().toISOString(),
      availableMarkets: [],
      hasMorePast: false,
    };
  }
}

export default async function SteamMovesPage() {
  const data = await getSteamMoves();

  return (
    <main className="container">
      <div className="steam-moves-page">
        <Breadcrumb items={[{ label: "Steam Moves" }]} />

        <header className="steam-moves-page__header">
          <h1 className="steam-moves-page__title">Steam Moves</h1>
          <p className="steam-moves-page__subtitle">
            Significant odds movements (&gt;5%) detected across bookmakers
          </p>
        </header>

        <SteamMovesClient
          initialData={data}
          availableMarkets={data.availableMarkets}
        />
      </div>
    </main>
  );
}
